version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  clipper:
    build: .
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/key.json
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    volumes:
      - ${WHERE_IS_MY_GOOGLE_CLOUD_PLATFORM_KEY_JSON_FILE}:/tmp/keys/key.json
      - ./:/opt/clipper
      - clipper-volume:/usr/share/clipper/data

volumes:
  clipper-volume:
